### ISSUE TITLE
Incompatible with Origins mod on 1.19.2

### ISSUE THREAD

**Issue by Poopooracoocoo** [DevLisuu/PrettyCapes-Fabric#7]
## Environment
Prism Launcher 7.2
Fabric Loader 0.14.24
Minecraft 1.19.2
Fabric API 0.76.1
Elytra Capes 2.3
Origins 1.7.1
Mod Menu 4.2.0-beta.2

## Steps to repro
1. Enable a cape in Minecraft Launcher or use the Capes mod
2. Create world
3. Select human origin
4. Press F5 or open inventory

## Actual behaviour

Hangs for about a minute then crashes

## Crash report
[crash-2023-11-21_13.30.49-client.txt](https://github.com/DevLisuu/ElytraCapes/files/13421162/crash-2023-11-21_13.30.49-client.txt)

<details>
<summary> Crash report</summary>

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-11-21 13:30:49
Description: Rendering entity in world

java.lang.ClassCastException: class net.minecraft.class_1770 cannot be cast to class net.minecraft.class_1799 (net.minecraft.class_1770 and net.minecraft.class_1799 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1d548a08)
	at org.spongepowered.asm.synthetic.args.Args$1.set(Args$1.java)
	at net.minecraft.class_979.args$zdn000$elytracapes$forceElytraRendering(class_979.java:1036)
	at net.minecraft.class_979.method_17161(class_979.java:35)
	at net.minecraft.class_979.method_4199(class_979.java:22)
	at net.minecraft.class_922.redirect$zcn000$apoli$preventFeatureRendering(class_922.java:563)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.synthetic.args.Args$1.set(Args$1.java)
	at net.minecraft.class_979.args$zdn000$elytracapes$forceElytraRendering(class_979.java:1036)
	at net.minecraft.class_979.method_17161(class_979.java:35)
	at net.minecraft.class_979.method_4199(class_979.java:22)
	at net.minecraft.class_922.redirect$zcn000$apoli$preventFeatureRendering(class_922.java:563)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 229
	Entity Name: Anon
	Entity's Exact location: -30.52, 71.25, 18.23
	Entity's Block location: World: (-31,71,18), Section: (at 1,7,2 in -2,4,1; chunk contains blocks -32,-64,16 to -17,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@33c3dad9
	Location: 3.37,-3.19,-1.49 - World: (3,-4,-2), Section: (at 3,12,14 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: -113.84601
	Delta: 0.14000416
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['Anon'/229, l='ClientLevel', x=-30.52, y=71.25, z=18.23]]
	Chunk stats: 961, 571
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,0), Section: (at 0,2,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3477 game time, 3477 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2121535992 bytes (2023 MiB) / 4001366016 bytes (3816 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: whiskey Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2121
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22973.61
	Virtual memory used (MB): 20619.78
	Swap memory total (MB): 15031.48
	Swap memory used (MB): 2512.16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		elytracapes: Elytra Capes 2.3-1.19.2
			cloth-config: Cloth Config v8 8.0.75
				cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.76.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.24
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				cardinal-components-base: Cardinal Components API (base) 5.0.1
				cardinal-components-entity: Cardinal Components API (entities) 5.0.1
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 31.0.101.2121, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Anon'/229, l='ServerLevel[New World]', x=-30.52, y=71.25, z=18.23]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

</details>

## Log
[latest.log](https://github.com/DevLisuu/ElytraCapes/files/13421181/latest.log)

<details> 
<summary>Log </summary>

```
[13:28:20] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.24
[13:28:20] [main/INFO]: Loading 66 mods:
	- elytracapes 2.3-1.19.2
	   \-- cloth-config 8.0.75
	        \-- cloth-basic-math 0.6.1
	- fabric-api 0.76.1+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.19.2
	- modmenu 4.2.0-beta.2
	- origins 1.7.1
	   |-- apoli 2.6.1
	   |    |-- additionalentityattributes 1.0.0+1.19
	   |    |-- calio 1.7.0
	   |    |-- cardinal-components-base 5.0.1
	   |    |-- cardinal-components-entity 5.0.1
	   |    |-- cloth-config 8.0.75
	   |    |    \-- cloth-basic-math 0.6.1
	   |    \-- playerabilitylib 1.6.0
	   \-- reach-entity-attributes 2.3.0
[13:28:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Anon/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:28:21] [main/INFO]: Compatibility level set to JAVA_17
[13:28:31] [main/INFO]: Building optimized datafixer
[13:28:38] [main/INFO]: apoli.mixins.json:ItemSlotArgumentTypeAccessor from mod apoli->@Accessor[FIELD_GETTER]::getSlotNamesToSlotCommandId()Ljava/util/Map; should be static as its target is
[13:28:40] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:28:42] [Render thread/INFO]: Setting user: Anon
[13:28:44] [Render thread/INFO]: Apoli 2.6.1 has initialized. Ready to power up your game!
[13:28:45] [Render thread/INFO]: Origins 1.7.1 is initializing. Have fun!
[13:28:47] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[13:28:48] [Worker-Main-8/INFO]: Checking mod updates...
[13:28:49] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[13:28:54] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Additionalentityattributes, Apoli, Calio, Cardinal Components API (base), Cardinal Components API (entities), Cloth Config v8, Elytra Capes, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Mod Menu, Origins, Pal, Reach Entity Attributes)
[13:29:00] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:29:00] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:29:00] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[13:29:00] [Render thread/INFO]: Sound engine started
[13:29:01] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[13:29:01] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:29:01] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:29:01] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:29:01] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:29:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:29:01] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:29:05] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:29:06] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[13:29:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:29:06] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:29:17] [Render thread/INFO]: Loaded 7 recipes
[13:29:18] [Render thread/INFO]: Loaded 1181 advancements
[13:29:18] [Render thread/INFO]: Finished loading powers from data files. Registry contains 76 powers.
[13:29:18] [Render thread/INFO]: Finished loading origins from data files. Registry contains 11 origins.
[13:29:18] [Render thread/INFO]: Trying to read layer file: origins:origin
[13:29:18] [Render thread/INFO]: Finished loading origin layers from data files. Read 1 layers.
[13:29:20] [Render thread/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 7.610 ms
[13:29:20] [Server thread/INFO]: Starting integrated minecraft server version 1.19.2
[13:29:20] [Server thread/INFO]: Generating keypair
[13:29:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:33] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:34] [Render thread/INFO]: Preparing spawn area: 0%
[13:29:34] [Render thread/INFO]: Preparing spawn area: 2%
[13:29:35] [Render thread/INFO]: Preparing spawn area: 6%
[13:29:35] [Render thread/INFO]: Preparing spawn area: 10%
[13:29:36] [Render thread/INFO]: Preparing spawn area: 10%
[13:29:36] [Render thread/INFO]: Preparing spawn area: 10%
[13:29:37] [Render thread/INFO]: Preparing spawn area: 26%
[13:29:37] [Render thread/INFO]: Preparing spawn area: 82%
[13:29:38] [Render thread/INFO]: Preparing spawn area: 87%
[13:29:38] [Render thread/INFO]: Time elapsed: 16555 ms
[13:29:39] [Server thread/INFO]: Changing view distance to 12, from 10
[13:29:39] [Server thread/INFO]: Changing simulation distance to 12, from 0
[13:29:42] [Server thread/INFO]: Anon[local:E:d02fce72] logged in with entity id 229 at (-30.523065282824064, 71.2546860896886, 18.22852005417668)
[13:29:42] [Server thread/INFO]: Anon joined the game
[13:29:42] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2989ms or 59 ticks behind
[13:29:47] [Render thread/INFO]: Loaded 5 advancements
[13:30:00] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2874ms or 57 ticks behind
[13:30:05] [Server thread/INFO]: Stopping server
[13:30:05] [Server thread/INFO]: Saving players
[13:30:05] [Server thread/INFO]: Saving worlds
[13:30:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[13:30:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[13:30:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[13:30:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[13:30:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:30:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:30:47] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[13:30:49] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1568) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1316) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1770 cannot be cast to class net.minecraft.class_1799 (net.minecraft.class_1770 and net.minecraft.class_1799 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1d548a08)
	at org.spongepowered.asm.synthetic.args.Args$1.set(Args$1.java) ~[?:?]
	at net.minecraft.class_979.args$zdn000$elytracapes$forceElytraRendering(class_979.java:1036) ~[client-intermediary.jar:?]
	at net.minecraft.class_979.method_17161(class_979.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_979.method_4199(class_979.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.redirect$zcn000$apoli$preventFeatureRendering(class_922.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 14 more
```

</details>

Reddit post that prompted me to report this: https://www.reddit.com/r/fabricmc/comments/17yl2om/having_a_hard_time_finding_the_root_of_this_crash/

**Comment by LisuuDev** [comment]
I will look into it
